language: python
python:
- '2.7'
branches:
  only:
  - master
install:
- pip install -r requirements.txt
script:
- make publish
deploy:
  provider: pages
  repo: bheal521.github.io
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN