branches:
  only:
  - master
language: python
python:
- 2.7
install:
- pip install -r requirements.txt --index-url
script:
- make html
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
  - secure: W9jdJcVLMok2QnSWn94bkBZL6yiP88paWBSQvj5pNwx6rMA/KAuAmEDTmxWCRpvte9CP1mTpPgNRwn7UhhmZsw4f1AKEAClxNbpbVUhiISW+LoVmlkhw//fp+qGplhun2ID9sJpfjsgun5Ue4+dcpvI2rHP17lC5ZgJBj3fx85M=
  - secure: EuleRVAaoed/C7mn6swpagRyfCf/ffhvavamXpqAx2KnbnAY1HX9sRFO8E2zCnjLLLz6ShgoWSNA4cloFnCbX41XbOnPXuUJkyBrV61X4twvVOcoDw/w2KVZfyhJ9umU5Ci4rr8kkGgIw8RPu8hFXP/0vVCk/I43t2K0KDshXrs=
  - secure: f+v3SHN8Yqebx+vLvlDEI5KYZ1476Oxlf2Jr44KndQyiBu4VwWJfIc7TfWVl5qyOkdnz8Fgni4qXPhJB+3RfNgpt/YpGiHtArqKOrPGS/dyozH863dgdEkTbpolOZnmzUZTEDgaB9owzhekXfcCR74X7GqMp+BAFv5d/h4WXp3NaXjiO7qQu9B8Tb3SeDqyRxD8li+TjAnAjjCuvgwDtv08b7nstu9+vxIq+lN4QY41IQJWi9L+HAFQwf+P+UkYwJbsmnJcMhRf7unIrSsGtmLkcjeDPAgYcQ7f6pHfgceVju3CX1u1HKPpQpcRDHJMfJ0HVT45bBfEPfszdCEfnl5pKjd5nVG3WQhNxzx+3WkWvr704XwthdSRmmmF2QkwOWfpWeao8tcouo21jPpeX47/S/e40TA5zIYnNd9jGup4qWjv65hZZ8lbMv9f6Dpg8rAQ3QEDX1w4v0S6EojKtq7HdUyVjBeL6eWR3vz5/lazmiAzQpFdXg4LOFFqObYErHhYVkDgHVrZ4PjTRwE3PuABup4l9y1xvObsQCSJoDDszI3ffFW+jG+N7d/J3Ui8sL34BWHnR1A6QAivyVXuZ9MCKbtV3jD6h9naN0TKlpym9rM+94hH1+ytGKYddJcyFwIrbCBHlpagpHwIOZYIi8cSHzbtqktE4Fqv8AwTVD3I=
before_install:
- git submodule update --init --recursive
after_success: bash deploy.sh
