language: python
python:
- '2.7'
branches:
  only:
  - master
install:
- pip install -r requirements.txt
- make download
script:
- make publish
deploy:
  provider: pages
  repo: bheal521/bheal521.github.io
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  on:
    branch: master